<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "main_base"
 *
 * Auto generated by Extension Builder 2018-10-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Frontend Base Extension',
    'description' => 'Extension for Frontend Actions, Overrides of other Extensions, Site Layouts Templates and Assets',
    'category' => 'fe',
    'author' => 'Ante Leventic',
    'author_email' => 'ante.leventic@web.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
